# Generated by Django 4.1.1 on 2022-09-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='catagory',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
