# Generated by Django 4.1.1 on 2022-09-21 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_search', '0002_course_catagory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='catagory',
            new_name='category',
        ),
    ]
